# Generated by Django 3.0.5 on 2020-04-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0002_auto_20200410_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='input_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/inputs/main/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='input_image_thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/inputs/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_finished',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
