# Generated by Django 3.0.5 on 2020-04-10 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificatino',
            new_name='Notification',
        ),
    ]
