# Generated by Django 3.0.5 on 2020-04-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0003_auto_20200414_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner_feedback',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
