# Generated by Django 3.0.5 on 2020-04-17 01:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0004_auto_20200414_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('max_tried', models.IntegerField(default=3)),
                ('code', models.CharField(default='knuzot', max_length=6)),
            ],
        ),
    ]
