# Generated by Django 3.1.13 on 2024-03-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0005_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='code',
            field=models.CharField(default='us2mdb', max_length=6),
        ),
    ]
